services:
  syncthing:
    container_name: syncthing
    image: syncthing/syncthing
    hostname: syncthing-${SERVER_NAME}
    #network_mode: host
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      #- STGUIADDRESS=0.0.0.0:8384
    volumes:
      - ${STORAGE_PATH}/syncthing:/var/syncthing
      - ${STORAGE_PATH}/common:/mnt/common

    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped