services:
  nginx:
    container_name: nginx
    image: jc21/nginx-proxy-manager:latest
    volumes:
      - ${STORAGE_PATH}/nginx/data:/data
      - ${STORAGE_PATH}/nginx/letsencrypt:/etc/letsencrypt
      - ${STORAGE_PATH}/nginx/html:/usr/share/nginx/html # Web server files
    restart: unless-stopped
    # These ports are in format <host-port>:<container-port>
    ports:
      - 80:80 # Public HTTP Port
      - 443:443 # Public HTTPS Port
      - 81:81 # Admin Web Port